"""TaskProtocol —— Task Runtime 抽象接口"""

from __future__ import annotations
from abc import ABC, abstractmethod
from core.task.models import TaskRequest, TaskResult, TaskInfo


class TaskProtocol(ABC):
    """Task Runtime 抽象接口"""

    @abstractmethod
    async def initialize(self) -> None: ...
    @abstractmethod
    async def create_task(self, request: TaskRequest) -> TaskInfo: ...
    @abstractmethod
    async def run(self, task_id: str) -> TaskResult: ...
    @abstractmethod
    async def pause(self, task_id: str) -> bool: ...
    @abstractmethod
    async def resume(self, task_id: str) -> bool: ...
    @abstractmethod
    async def cancel(self, task_id: str) -> bool: ...
    @abstractmethod
    async def retry(self, task_id: str) -> bool: ...
    @abstractmethod
    async def destroy(self, task_id: str) -> bool: ...
    @abstractmethod
    async def query(self, task_id: str) -> TaskInfo | None: ...
    @abstractmethod
    async def list_tasks(self) -> list[TaskInfo]: ...
    @abstractmethod
    async def shutdown(self) -> None: ...
