"""Agent Runtime Protocol."""
from __future__ import annotations
from abc import ABC, abstractmethod
from core.agents.models import AgentRequest, AgentResponse, AgentInfo, AgentContext
class AgentRuntime(ABC):
    @abstractmethod
    async def initialize(self) -> None: ...
    @abstractmethod
    async def shutdown(self) -> None: ...
    @abstractmethod
    async def run(self, request: AgentRequest) -> AgentResponse: ...
    @abstractmethod
    async def build_context(self, request: AgentRequest) -> AgentContext: ...
    @abstractmethod
    async def invoke_llm(self, context: AgentContext) -> str: ...
    @abstractmethod
    async def invoke_tools(self, tool_names: list[str], context: AgentContext) -> dict[str, Any]: ...
    @abstractmethod
    async def after_response(self, request: AgentRequest, response: AgentResponse) -> None: ...
    @property
    @abstractmethod
    def info(self) -> AgentInfo: ...